_description: A basic flow to access and manipulate integer records
basic-storer:
  _description: A basic record storer that stores integers in a file.
  file_path: (str) The path to a file to store records
basic-storer-mode: (str) The mode to run basic-storer in (either 'include' or 'debug')
increment-1:
  _description: A basic flow update step to increment all records
  increment: (int) The amount to increment by
increment-1-mode: (str) The mode to run increment-1 in (either 'include', 'exclude',
  or 'debug')
increment-2:
  _description: A basic flow update step to increment all records
  increment: (int) The amount to increment by
increment-2-mode: (str) The mode to run increment-2 in (either 'include', 'exclude',
  or 'debug')
increment-3:
  _description: A basic flow update step to increment all records
  increment: (int) The amount to increment by
increment-3-mode: (str) The mode to run increment-3 in (either 'include', 'exclude',
  or 'debug')
new-integer:
  _description: A basic flow record step to add a (changing) new record.
new-integer-mode: (str) The mode to run new-integer in (either 'include', 'exclude',
  or 'debug')
num_threads: (int) The number of threads to use when running update and propagate
  steps
print-sum:
  _description: A basic flow propagate step to log the sum of all records
print-sum-mode: (str) The mode to run print-sum in (either 'include', 'exclude', or
  'debug')
