# ========================================================================
# lint-and-docs.yml
# ========================================================================
# GitHub Action to lint the source code and update the documentation

name: Linting and Documentation

permissions:
  contents: write

on:
  push:
    branches:    
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Checking style with Flake
      run: |
        python -m flake8 . \
          --require-plugins flake8-pydocstyle,pydoclint,flake8-annotations \
          --max-line-length 80 \
          --ignore DOC301,E731,W503,E203 \
          --exclude docs
    - name: Type check with MyPy
      run: |
        python -m mypy --strict . --exclude docs
    - name: Install documentation dependencies
      run: |
        pip install sphinx sphinx_rtd_theme myst_parser sphinx-togglebutton
    - name: Sphinx build
      run: |
        sphinx-build docs _build -b dirhtml
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      with:
        publish_branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _build/
        force_orphan: true